spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #  redis:
  #    host: ${REDIS_HOST:localhost}
  #    port: ${REDIS_PORT:6379}
  #    password: ${REDIS_PASSWORD:your-redis-password}

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  secret_key: test-key
  access_exp: 7200
  refresh_exp: 2630016
  header: Authorization
  prefix: Bearer

#cloud:
#  aws:
#    s3:
#      prefix: ${AWS_S3_PREFIX:/}
#      bucket: ${AWS_S3_BUCKET:LeaveLeave/}
#      base-image-url: ${AWS_S3_URL:LeaveLeave}
#    region:
#      static: ${AWS_S3_REGION:ap-northeast-2}
#    stack:
#      auto: false
#    credentials:
#      access-key: ${AWS_S3_ACCESS}
#      secret-key: ${AWS_S3_SECRET}
